version: '3.8'

services:
  frontend:   
    build: 
      context: ./example-frontend
    container_name: frontend
    ports:
      - 5000:5000

  backend:
    build: 
      context: ./example-backend
    container_name: backend
    ports:
     - 8080:8080