version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: exercise
    container_name: db_backend
    volumes:
      - ./database:/var/lib/postgresql/data
  frontend:   
    build: 
      context: ./example-frontend
    container_name: frontend
    ports:
      - 5000:5000
  backend:
    build: 
      context: ./example-backend
    container_name: backend
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: exercise
    ports:
     - 8080:8080
    depends_on:
      - db
  redis:
    image: redis
    restart: unless-stopped
volumes:
  database: