# Start from the python:3.8 image
FROM python:3.8

# Use /usr/src/app as our workdir
WORKDIR /urs/src/app

# Copy all of the source code
COPY . .

# Set entrypoint
ENTRYPOINT ["python"]

# Set command
CMD ["IUC.py"]
